; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:stm32f042k6t6]
platform = ststm32
board = nucleo_f042k6
board_build.mcu = stm32f042k6t6
board_build.f_cpu = 48000000L
framework = arduino
monitor_speed = 115200
build_flags =
	-DHAL_CAN_MODULE_ENABLED
	-I embedded-pio
	-Wall
	-Wextra
	-Werror=return-type
	-Wno-unused-parameter
lib_extra_dirs = ./embedded-pio
; STM32_CAN comes from embedded-pio/STM32_CAN
